### PR TITLE
Some cleanup

### PR DESCRIPTION
**Pull request by ilfreddy**
Removing unnecessary python notebooks.

### CODE REVIEW

**Comment by stigrj** [comment]
Just remove `python-3.6` from the workflow file

**Comment by stigrj** [comment]
3.10 shows up as 3.1??

**Comment by ilfreddy** [comment]
I will just remove it for now. Should one use a special syntax to be able to read 3.10 as 3.10 and not 3.1?

**Comment by stigrj** [comment]
`['3.10']` should fix it

**Comment by ilfreddy** [comment]
> `['3.10']` should fix it

It's not a bug... It's a feature ;-)

**Review by Christian48596 — APPROVED** [review]

**Pull request merged**
